# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: 'dockerpush'
    repository: 'keycloak-test'
    command: 'build'
    Dockerfile: './docker/Dockerfile'
    arguments: '-t keycloak-test:latest'
    

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: dockerpush
    repository: keycloak-test
    command: push
    tags: keycloak-test:latest
      

- script: docker images

# steps:
# - script: git switch -c feature/fixDockerfile && ls -la
# - script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_PULL_HOST